

export const SIGNUP_CLIENT = "SIGNUP_CLIENT"
export const SIGNIN_CLIENT = "SIGNIN_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_USERNAME = "RESET_USERNAME"
export const SIGNOUT_CLIENT = "SIGNOUT_CLIENT"
export const LOAD_CLIENT = "LOAD_CLIENT"
export const ERROR_CLIENT = "ERROR_CLIENT"
export const CURRENT_CLIENT = "CURRENT_CLIENT"